import type { TracingEvent } from '../types';

/**
 * Minimal reproduction extractor.
 * Given the hot subset of a trace, emit a self-contained Node.js script that
 * replays the same diagnostics_channel traffic (with real timestamps) so a
 * failing gate can be reproduced locally in one command.
 */

export interface ReproOptions {
  /** Channels to keep (default: all that appear in the events). */
  channels?: string[];
  /** Max number of events to embed (slice the tail). */
  maxEvents?: number;
}

const DEFAULT_MAX_EVENTS = 2000;

function renderValue(value: unknown): string {
  if (value === null || value === undefined) return 'undefined';
  if (typeof value === 'string') return JSON.stringify(value.slice(0, 500));
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    const inner = value.slice(0, 20).map(renderValue).join(', ');
    return value.length > 20 ? `[${inner}, ...]` : `[${inner}]`;
  }
  if (typeof value === 'object') {
    try {
      const body = JSON.stringify(value).slice(0, 2000);
      return `JSON.parse(${JSON.stringify(body)})`;
    } catch {
      return 'undefined';
    }
  }
  return 'undefined';
}

/** Picks the hottest subset of events (slowest / most recent) for embedding. */
export function selectReproEvents(events: TracingEvent[], options: ReproOptions = {}): TracingEvent[] {
  const channels = options.channels ? new Set(options.channels) : null;
  const filtered = channels ? events.filter(e => channels.has(e.channel)) : [...events];
  const max = options.maxEvents ?? DEFAULT_MAX_EVENTS;
  // Keep the slowest operations (they are what the gate complains about),
  // falling back to the most recent events.
  const withDuration = filtered.filter(e => e.duration != null && e.duration > 0)
    .sort((a, b) => (b.duration ?? 0) - (a.duration ?? 0));
  if (withDuration.length >= max) return withDuration.slice(0, max);
  const rest = filtered
    .filter(e => e.duration == null || e.duration <= 0)
    .slice(-Math.max(0, max - withDuration.length));
  return [...withDuration, ...rest];
}

/** Generates a runnable Node.js script that replays the given events. */
export function generateReproScript(events: TracingEvent[], options: ReproOptions = {}): string {
  const selected = selectReproEvents(events, options);
  const channelNames = [...new Set(selected.map(e => e.channel))];

  const parts: string[] = [];
  parts.push(`'use strict';`);
  parts.push(`// Generated by NodeVerdict — minimal reproduction for a failing performance gate.`);
  parts.push(`// Run with: node repro.mjs`);
  parts.push(`const { channel, tracingChannel } = require('node:diagnostics_channel');`);
  parts.push(``);
  parts.push(`const t0 = Date.now();`);
  parts.push(``);
  for (const name of channelNames) {
    parts.push(`const ${'chan' + String(channelNames.indexOf(name)).padStart(2, '0')} = channel(${JSON.stringify(name)});`);
  }
  parts.push(``);
  parts.push(`function emit(c, type, context) {`);
  parts.push(`  try {`);
  parts.push(`    if (type === 'start') c.publish(context);`);
  parts.push(`    else c.publish({ ...context, [type]: true });`);
  parts.push(`  } catch {}`);
  parts.push(`}`);
  parts.push(``);
  parts.push(`function run() {`);
  for (const ev of selected) {
    const idx = channelNames.indexOf(ev.channel);
    const delay = Math.max(0, Math.round(ev.timestamp));
    parts.push(`  setTimeout(() => emit(chan${String(idx).padStart(2, '0')}, ${JSON.stringify(ev.eventType)}, {`);
    parts.push(`    timestamp: t0 + ${delay},`);
    if (ev.duration != null) parts.push(`    duration: ${ev.duration},`);
    if (ev.error) parts.push(`    error: ${renderValue(ev.error)},`);
    parts.push(`    ${renderContext(ev.context)}`);
    parts.push(`  }), ${delay});`);
  }
  parts.push(`  setTimeout(() => { console.log('replayed ${selected.length} events; done.'); }, ${Math.max(0, Math.round((selected.at(-1)?.timestamp ?? 0))) + 100});`);
  parts.push(`}`);
  parts.push(``);
  parts.push(`run();`);
  return parts.join('\n');
}

function renderContext(context: Record<string, unknown>): string {
  const keys = Object.keys(context).slice(0, 12);
  const rendered = keys.map(k => `${JSON.stringify(k)}: ${renderValue(context[k])}`);
  return rendered.join(',\n    ');
}

/** Convenience: combine extraction + codegen in one call. */
export function buildReproScript(events: TracingEvent[], options?: ReproOptions): string {
  return generateReproScript(events, options);
}